# Generated by Django 4.2.6 on 2023-10-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_current_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='current_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
