# Generated by Django 4.2.6 on 2023-10-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_body_alter_post_current_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-current_time',)},
        ),
    ]
