# Generated by Django 4.2.6 on 2023-12-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-current_time',)},
        ),
    ]
